use std::{
    collections::BTreeMap,
    fs,
    path::{Path, PathBuf},
};

use serde::Deserialize;

#[derive(Debug, Deserialize)]
struct TokenFile {
    color: BTreeMap<String, String>,
    spacing: BTreeMap<String, String>,
    typography: TypographyTokens,
    radius: BTreeMap<String, String>,
    shadow: BTreeMap<String, String>,
    border: BorderTokens,
    opacity: BTreeMap<String, String>,
    z_index: BTreeMap<String, String>,
    motion: MotionTokens,
    icon: BTreeMap<String, String>,
    shell: ShellTokens,
}

#[derive(Debug, Deserialize)]
struct TypographyTokens {
    family: BTreeMap<String, String>,
    size: BTreeMap<String, String>,
    weight: BTreeMap<String, String>,
    line_height: BTreeMap<String, String>,
}

#[derive(Debug, Deserialize)]
struct BorderTokens {
    width: BTreeMap<String, String>,
}

#[derive(Debug, Deserialize)]
struct MotionTokens {
    duration: BTreeMap<String, String>,
    easing: BTreeMap<String, String>,
}

#[derive(Debug, Deserialize)]
struct ShellTokens {
    taskbar: BTreeMap<String, String>,
    titlebar: BTreeMap<String, String>,
    window_chrome: BTreeMap<String, String>,
    resize_handle: BTreeMap<String, String>,
}

fn sanitize_ident(raw: &str) -> String {
    let mut ident = raw.replace('-', "_").to_ascii_uppercase();
    if ident
        .chars()
        .next()
        .map(|ch| ch.is_ascii_digit())
        .unwrap_or(false)
    {
        ident = format!("N_{ident}");
    }
    ident
}

fn push_const_block(buffer: &mut String, prefix: &str, values: &BTreeMap<String, String>) {
    for (key, value) in values {
        let ident = sanitize_ident(key);
        buffer.push_str(&format!("pub const {prefix}_{ident}: &str = {value:?};\n"));
    }
}

fn push_css_vars(buffer: &mut String, section: &str, values: &BTreeMap<String, String>) {
    for (key, value) in values {
        buffer.push_str(&format!("  --origin-{section}-{key}: {value};\n"));
    }
}

fn ensure_parent(path: &Path) {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).expect("create parent dir");
    }
}

fn write_if_changed(path: &Path, contents: &str) {
    ensure_parent(path);
    let current = fs::read_to_string(path).ok();
    if current.as_deref() != Some(contents) {
        fs::write(path, contents).expect("write generated file");
    }
}

fn main() {
    println!("cargo:rerun-if-changed=tokens/tokens.toml");

    let manifest_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("manifest dir"));
    let tokens_path = manifest_dir.join("tokens/tokens.toml");
    let raw = fs::read_to_string(&tokens_path).expect("read tokens.toml");
    let tokens: TokenFile = toml::from_str(&raw).expect("parse tokens.toml");

    let mut rust = String::from("// Generated by system_ui/build.rs. Do not edit by hand.\n");
    rust.push_str("pub const BASELINE_STYLE_ID: &str = \"origin-baseline\";\n");
    push_const_block(&mut rust, "COLOR", &tokens.color);
    push_const_block(&mut rust, "SPACE", &tokens.spacing);
    push_const_block(&mut rust, "RADIUS", &tokens.radius);
    push_const_block(&mut rust, "SHADOW", &tokens.shadow);
    push_const_block(&mut rust, "OPACITY", &tokens.opacity);
    push_const_block(&mut rust, "Z_INDEX", &tokens.z_index);
    push_const_block(&mut rust, "ICON", &tokens.icon);
    push_const_block(&mut rust, "TYPE_FAMILY", &tokens.typography.family);
    push_const_block(&mut rust, "TYPE_SIZE", &tokens.typography.size);
    push_const_block(&mut rust, "TYPE_WEIGHT", &tokens.typography.weight);
    push_const_block(
        &mut rust,
        "TYPE_LINE_HEIGHT",
        &tokens.typography.line_height,
    );
    push_const_block(&mut rust, "BORDER_WIDTH", &tokens.border.width);
    push_const_block(&mut rust, "MOTION_DURATION", &tokens.motion.duration);
    push_const_block(&mut rust, "MOTION_EASING", &tokens.motion.easing);
    push_const_block(&mut rust, "SHELL_TASKBAR", &tokens.shell.taskbar);
    push_const_block(&mut rust, "SHELL_TITLEBAR", &tokens.shell.titlebar);
    push_const_block(
        &mut rust,
        "SHELL_WINDOW_CHROME",
        &tokens.shell.window_chrome,
    );
    push_const_block(
        &mut rust,
        "SHELL_RESIZE_HANDLE",
        &tokens.shell.resize_handle,
    );

    let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR"));
    write_if_changed(&out_dir.join("origin_tokens_generated.rs"), &rust);

    let mut css =
        String::from("/* Generated from ui/crates/system_ui/tokens/tokens.toml */\n:root {\n");
    push_css_vars(&mut css, "color", &tokens.color);
    push_css_vars(&mut css, "space", &tokens.spacing);
    push_css_vars(&mut css, "radius", &tokens.radius);
    push_css_vars(&mut css, "shadow", &tokens.shadow);
    push_css_vars(&mut css, "opacity", &tokens.opacity);
    push_css_vars(&mut css, "z", &tokens.z_index);
    push_css_vars(&mut css, "icon", &tokens.icon);
    push_css_vars(&mut css, "type-family", &tokens.typography.family);
    push_css_vars(&mut css, "type-size", &tokens.typography.size);
    push_css_vars(&mut css, "type-weight", &tokens.typography.weight);
    push_css_vars(&mut css, "type-line-height", &tokens.typography.line_height);
    push_css_vars(&mut css, "border-width", &tokens.border.width);
    push_css_vars(&mut css, "motion-duration", &tokens.motion.duration);
    push_css_vars(&mut css, "motion-easing", &tokens.motion.easing);
    push_css_vars(&mut css, "shell-taskbar", &tokens.shell.taskbar);
    push_css_vars(&mut css, "shell-titlebar", &tokens.shell.titlebar);
    push_css_vars(&mut css, "shell-window-chrome", &tokens.shell.window_chrome);
    push_css_vars(&mut css, "shell-resize-handle", &tokens.shell.resize_handle);
    css.push_str("}\n");
    css.push_str(
        "\n:root[data-high-contrast=\"true\"] {\n  --origin-color-surface: #ffffff;\n  --origin-color-surface-muted: #f4f4f4;\n  --origin-color-surface-elevated: #ffffff;\n  --origin-color-text-primary: #000000;\n  --origin-color-text-secondary: #202020;\n  --origin-color-border-strong: #000000;\n  --origin-color-border-subtle: #444444;\n  --origin-color-accent: #0038ff;\n  --origin-shadow-window: none;\n  --origin-shadow-overlay: none;\n}\n",
    );
    css.push_str(
        "\n:root[data-reduced-motion=\"true\"] {\n  --origin-motion-duration-fast: 0ms;\n  --origin-motion-duration-standard: 0ms;\n  --origin-motion-duration-slow: 0ms;\n}\n",
    );

    let site_dir = manifest_dir.parent().expect("ui/crates").join("site");
    write_if_changed(&site_dir.join("src/generated/tokens.css"), &css);

    let tailwind =
        "// Generated from ui/crates/system_ui/tokens/tokens.toml\nmodule.exports = {\n  content: [\"./src/**/*.rs\", \"./src/**/*.html\"],\n  theme: {\n    extend: {\n      colors: {\n        canvas: \"var(--origin-color-canvas)\",\n        desktop: \"var(--origin-color-desktop)\",\n        surface: \"var(--origin-color-surface)\",\n        accent: \"var(--origin-color-accent)\",\n        text: { primary: \"var(--origin-color-text-primary)\", secondary: \"var(--origin-color-text-secondary)\" },\n      },\n      spacing: {\n        1: \"var(--origin-space-1)\",\n        2: \"var(--origin-space-2)\",\n        3: \"var(--origin-space-3)\",\n        4: \"var(--origin-space-4)\",\n        5: \"var(--origin-space-5)\",\n        6: \"var(--origin-space-6)\",\n        8: \"var(--origin-space-8)\",\n      },\n      borderRadius: {\n        sm: \"var(--origin-radius-sm)\",\n        md: \"var(--origin-radius-md)\",\n        lg: \"var(--origin-radius-lg)\",\n        xl: \"var(--origin-radius-xl)\",\n      },\n      boxShadow: {\n        panel: \"var(--origin-shadow-panel)\",\n        window: \"var(--origin-shadow-window)\",\n        overlay: \"var(--origin-shadow-overlay)\",\n      },\n      fontFamily: {\n        sans: [\"var(--origin-type-family-sans)\"],\n        mono: [\"var(--origin-type-family-mono)\"],\n      },\n      transitionDuration: {\n        fast: \"var(--origin-motion-duration-fast)\",\n        DEFAULT: \"var(--origin-motion-duration-standard)\",\n        slow: \"var(--origin-motion-duration-slow)\",\n      },\n      transitionTimingFunction: {\n        standard: \"var(--origin-motion-easing-standard)\",\n        emphasized: \"var(--origin-motion-easing-emphasized)\",\n      },\n    },\n  },\n  corePlugins: { preflight: false },\n};\n"
            .to_string();
    write_if_changed(&site_dir.join("tailwind.config.js"), &tailwind);
}
